In [6]:
import pandas as pd

df = pd.read_csv("./data/raw/trident_treats_raw.csv")

df.head()

,Name,Email Address,Nickname,Home Address,Password,Salt,Birthdate,Phone Number,Store ID,Gender,Account Type,Branch
0,José Clarke,kendrabest760@tridenttreats.bb,ken41,"36 Grazettes Main Road, St. Philip, Barbados",n](l.2edlB,oGMbJmTP,1999-09-14,246-425-8359,1603.0,Female,Standard,Oistins
1,Zoë Callender,aliciajordan285@bdsconnect.bb,ali37,"27 Bank Hall, St. Philip, Barbados",lWmTS:Hf~6,Ih7yfJs1,1995-10-28,246-570-4150,1721.0,Male,Standard,Oistins
2,Renée Best,omarholder876@bdsconnect.bb,oma22,"72 Country Road, St. Philip, Barbados",6>UuVTA\I`,7RPeMOkI,2001-04-06,246-673-7216,1276.0,Other,Staff,Six Roads
3,François Holder,devinjordan864@caribmail.com,dev39,"207 Atlantic Shores, St. Philip, Barbados",OZIiB+|OB@,Fz46PDjq,1963-04-24,246-774-9830,1269.0,Other,Staff,Wildey
4,Mårlon Forde,mårlongittens371@bdsconnect.bb,mår27,"127 Two Mile Hill, St. Philip, Barbados",lgot=u^2/i,yyMDHqJ3,1955-11-24,246-317-9797,1768.0,Female,Staff,Speightstown

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           300 non-null    str
 1   Email Address  300 non-null    str
 2   Nickname       298 non-null    str
 3   Home Address   298 non-null    str
 4   Password       298 non-null    str
 5   Salt           298 non-null    str
 6   Birthdate      298 non-null    str
 7   Phone Number   298 non-null    str
 8   Store ID       298 non-null    float64
 9   Gender         298 non-null    str
 10  Account Type   298 non-null    str
 11  Branch         298 non-null    str
dtypes: float64(1), str(11)
memory usage: 28.3 KB

In [8]:
df.describe()

          Store ID
count   298.000000
mean   1504.785235
std     284.016208
min    1006.000000
25%    1276.000000
50%    1500.000000
75%    1751.500000
max    1999.000000

In [9]:
df.isnull().sum()

Name             0
Email Address    0
Nickname         2
Home Address     2
Password         2
Salt             2
Birthdate        2
Phone Number     2
Store ID         2
Gender           2
Account Type     2
Branch           2
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

df.columns = df.columns.str.lower().str.replace(" ", "_")

In [11]:
df = df.drop_duplicates()

In [15]:
df = df.fillna

In [32]:
import pandas as pd
import os

# Load the raw dataset
df = pd.read_csv("./data/raw/trident_treats_raw.csv")

# Basic cleaning
df.columns = df.columns.str.lower().str.replace(" ", "_")
df = df.drop_duplicates()
df = df.dropna()

# Make sure the cleaned folder exists
os.makedirs("../data/cleaned", exist_ok=True)

# Save cleaned dataset
df.to_csv("./data/cleaned/trident_treats_clean.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.